"""Argument parser for the public ut-agent command line."""
from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ut-agent", description="ut-agent CLI")
    sub = parser.add_subparsers(dest="cmd", required=True)

    parse = sub.add_parser("parse", help="解析源码 → FunctionIR JSON")
    parse.add_argument("source")
    parse.add_argument("-f", "--function")
    parse.add_argument("-I", "--include", action="append", default=[])
    parse.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    parse.add_argument("--include-config")
    parse.add_argument("--context-source", action="append", default=[])
    parse.add_argument("--watch-macro", action="append", default=[])
    parse.add_argument("--clang-extractor", default=None)
    parse.add_argument("-o", "--output")
    parse.add_argument("--list", action="store_true")

    gen = sub.add_parser("gen", help="解析 + 生成 stub 源码与用例表 CSV")
    gen.add_argument("source")
    gen.add_argument("-f", "--function", required=True)
    gen.add_argument("-I", "--include", action="append", default=[])
    gen.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    gen.add_argument("--include-config")
    gen.add_argument("--context-source", action="append", default=[])
    gen.add_argument("--call-max", type=int, default=5)
    gen.add_argument("--cfg-display", default="")
    gen.add_argument("--reference-csv")
    gen.add_argument("--rules")
    gen.add_argument("--manifest", dest="project_manifest",
                     help="项目 manifest；指定后启用锁定 TestBaseline 流水线")
    gen.add_argument("--config-root",
                     help="TestBaseline/ProjectRulePack 配置根目录")
    gen.add_argument("--clang-extractor", default=None)
    gen.add_argument("--intent-manifest")
    gen.add_argument("--winams-source-label", default="")
    gen.add_argument("--winams-title", default="")
    gen.add_argument("--out", default=".")

    batch = sub.add_parser("batch", help="批量跑一个模块的全部函数")
    batch.add_argument("source")
    batch.add_argument("-f", "--functions")
    batch.add_argument("-I", "--include", action="append", default=[])
    batch.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    batch.add_argument("--include-config")
    batch.add_argument("--clang-extractor", default=None)
    batch.add_argument("--out", default=".build/batch")
    batch.add_argument("--exec-limit", type=int, default=20000)

    index = sub.add_parser("psd-project", help="用项目索引生成全部 WinAMS TestCsv")
    index.add_argument("index_csv")
    index.add_argument("--product-root", required=True)
    index.add_argument("--out", required=True)
    index.add_argument("--reference-root")
    index.add_argument("--baseline-manifest",
                       help="锁定 TestBaseline 的项目 context manifest")
    index.add_argument("--config-root")
    index.add_argument("--check-golden", action="store_true")
    index.add_argument("--call-max", type=int, default=5)
    index.add_argument("--extract-timeout", type=float, default=600.0)
    index.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    index.add_argument("--rules")
    index.add_argument("--clang-extractor", default=None)

    arm = sub.add_parser("arm-build", help="使用 Arm GNU Toolchain 生成 ARM ELF")
    arm.add_argument("source", nargs="+")
    arm.add_argument("-I", "--include", action="append", default=[])
    arm.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    arm.add_argument("-o", "--output", required=True)
    arm.add_argument("--compiler")
    arm.add_argument("--cpu", default="cortex-m4")
    arm.add_argument("--entry")
    arm.add_argument("--strict-link", action="store_true")
    arm.add_argument("--omf-output")
    arm.add_argument("--omf-converter")
    arm.add_argument("--dwarf-version", type=int, choices=(4, 5), default=5)

    project = sub.add_parser("project", help="只用 Soft + manifest 生成 WinAMS 工程")
    project.add_argument("soft")
    project.add_argument("--manifest", required=True)
    project.add_argument("--baseline-manifest",
                         help="锁定 TestBaseline 的项目 context manifest")
    project.add_argument("--config-root")
    project.add_argument("--out", required=True)
    project.add_argument("--no-build", action="store_true")
    project.add_argument("--run", action="store_true")
    project.add_argument("--check-golden", action="store_true")
    project.add_argument("--compiler")
    project.add_argument("--omf-converter")
    project.add_argument("--cpu")
    project.add_argument("--reference-out")
    project.add_argument("--reference-xlo")
    project.add_argument("--reference-define-var")
    project.add_argument("--reference-mpu", default="RH850(GHS)")
    project.add_argument("--winams", default="/mnt/c/WinAMS/BIN/SSTManager.exe")
    project.add_argument("--timeout", type=float, default=120.0)
    project.add_argument("--clang-extractor", default=None)
    project.add_argument("--rules")

    rules = sub.add_parser("rules", help="规则包归纳与审查辅助")
    rules_sub = rules.add_subparsers(dest="rules_cmd", required=True)
    infer = rules_sub.add_parser("infer", help="从人工 TestCsv 归纳候选规则")
    infer.add_argument("source")
    infer.add_argument("-f", "--function", required=True)
    infer.add_argument("--golden", required=True)
    infer.add_argument("-I", "--include", action="append", default=[])
    infer.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    infer.add_argument("--include-config")
    infer.add_argument("--clang-extractor", default=None)
    infer.add_argument("-o", "--output", required=True)
    infer.add_argument("--merge", action="store_true")

    collect = rules_sub.add_parser("collect", help="采集 WinAMS TestCsv 语料")
    collect.add_argument("winams_root")
    collect.add_argument("--base-profile", default="PSD再構築")
    collect.add_argument("--profile-version", default="PSD再構築-v1")
    collect.add_argument("--mcdc-enabled", action=argparse.BooleanOptionalAction, default=True)
    collect.add_argument("--exception", action="append", default=[], dest="exceptions")
    collect.add_argument("--source-root")
    collect.add_argument("--include-root")
    collect.add_argument("-I", "--include", action="append", default=[])
    collect.add_argument("-D", "--define", action="append", default=[], metavar="NAME=VALUE")
    collect.add_argument("--include-config")
    collect.add_argument("--max-samples", type=int)
    collect.add_argument("-o", "--output", required=True)
    collect.add_argument("--candidate-pack")

    compress = rules_sub.add_parser("compress", help="压缩为跨函数/跨项目语义族")
    compress.add_argument("corpus", nargs="+")
    compress.add_argument("-o", "--output", required=True)
    compress.add_argument("--project-id", action="append", dest="project_ids")
    compress.add_argument("--min-functions", type=int, default=2)
    compress.add_argument("--min-projects", type=int, default=2)

    check = rules_sub.add_parser("check", help="检查规则包结构和审批状态")
    check.add_argument("pack")
    check.add_argument("--require-approved", action="store_true")
    approve = rules_sub.add_parser("approve", help="将候选规则复制为已审批规则包")
    approve.add_argument("pack")
    approve.add_argument("-o", "--output", required=True)
    approve.add_argument("--authority", required=True)
    approve.add_argument("--reason", required=True)
    approve.add_argument("--id", action="append", dest="rule_ids")

    artifacts = sub.add_parser("artifacts", help="只读分析构建产物证据")
    artifacts.add_argument("root")
    artifacts.add_argument("--map", dest="map_path")
    artifacts.add_argument("--mot", dest="mot_path")
    artifacts.add_argument("--out", dest="out_path")
    artifacts.add_argument("--xlo", dest="xlo_path")
    artifacts.add_argument("--symbol", action="append", default=[])
    artifacts.add_argument("-o", "--output")
    return parser
